DROP TABLE IF EXISTS user_streaks CASCADE;
DROP TABLE IF EXISTS points CASCADE;
DROP TABLE IF EXISTS attempts CASCADE;
DROP TABLE IF EXISTS challenges CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS difficulty_level;
DROP TYPE IF EXISTS challenge_type;
DROP TYPE IF EXISTS user_role;